metadata/objects/ClubEvent__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/objects/Performer__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>ClubEvent__c</referenceTo>
        <relationshipLabel>Performers</relationshipLabel>
        <relationshipName>Performers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Performer</label>
    <nameField>
        <label>Performer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/CreatePerformerController.cls
global class CreatePerformerController{
    public String performerName {get; set;}
    public String performerEmail {get; set;}
    ClubEvent__c event;
    
    public CreatePerformerController(ApexPages.StandardController stdController) {
        this.event = (ClubEvent__c)stdController.getRecord();
    }
    
    @RemoteAction
    global static Id insertPerformer(Id eventId, String name, String email) {
        Performer__c p = new Performer__c(
           	Name = name,
            Email__c = email,
            Event__c = eventId
        );
        
        insert p;
        
        return p.Id;
    }
    
    @RemoteAction
    public static Id makeContentPublic(String contentVersionId) {
        ContentVersion cv = [SELECT ContentDocumentId 
                             FROM ContentVersion 
                             WHERE Id = :contentVersionId];
        ContentDocumentLink cdl = new ContentDocumentLink(
            ContentDocumentId = cv.ContentDocumentId, 
            LinkedEntityId = UserInfo.getOrganizationId(), 
            ShareType = 'V');
        insert cdl;
        
        return cv.ContentDocumentId;
    }
}