metadata/objects/Performer__c.object
<CustomObject>
    <fields>
        <fullName>Youtube_URL__c</fullName>
        <label>Youtube URL</label>
        <type>Url</type>
    </fields>
    <label>Performer</label>
    <nameField>
        <label>Performer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/PerformerVideoController.cls
public class PerformerVideoController {
    Performer__c performer;
    
    public PerformerVideoController(ApexPages.StandardController stdController) {
        List<String> fields = new String[1];
        fields[0] = 'Youtube_URL__c';
        stdController.addFields(fields);
        
        this.performer = (Performer__c)stdController.getRecord();
    }
    
    public String getYouTubeEmbedLink() {
        return  (performer.Youtube_URL__c != null) 
            ? 'https://www.youtube.com/embed/' + performer.Youtube_URL__c.split('=')[1]
            : 'about:blank';
    }
}